# Generated by Django 2.0.13 on 2019-05-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_vpn_key'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='portaldevice',
            name='openwisp_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Device'),
        ),
    ]
