# Generated by Django 2.0.13 on 2019-05-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_vpn_key'),
        ('portal', '0002_auto_20190520_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoovaDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coova', models.BooleanField(default=False)),
                ('openwisp_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='portaldevice',
            name='openwisp_device',
        ),
    ]
