# Generated by Django 2.0.13 on 2019-05-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190520_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='coovadevice',
            name='my_controller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Controller'),
            preserve_default=False,
        ),
    ]
