# Generated by Django 2.0.13 on 2019-05-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_coovadevice_my_controller'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoovaDeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('coova_device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.CoovaDevice')),
            ],
        ),
    ]
