# Generated by Django 2.0.13 on 2019-09-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_connectiontable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiontable',
            old_name='remaining_time',
            new_name='remaining_time_seconds',
        ),
    ]
