# Generated by Django 2.0.13 on 2019-09-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_auto_20190920_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='radacct',
            name='acctinterval',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
