# Generated by Django 2.0.13 on 2019-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0003_radacct_acctinterval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radacct',
            name='acctstarttime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radacct',
            name='acctstoptime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
